'use strict';

module.exports = {
  "antifreeze" : {
    "location": "in the garage",
    "common_name": "Antifreeze",
    "hazardous_ingredient": "Ethylene Glycol",
    "acute_health": "Hazardous in case of ingestion. Slightly hazardous in case of skin contact (irritant, permeator), of eye contact (irritant), of inhalation. Severe over-exposure can result in death",
    "chronic_health": "The substance may be toxic to kidneys, liver, central nervous system. Repeated or prolonged exposure to the substance can produce target organs damage. Repeated exposure to a highly toxic material may produce general deterioration of health by an accumulation in one or many human organs",
    "eye_contact": "Check for and remove any contact lenses. In case of contact, immediately flush eyes with plenty of water for at least 15 minutes. Cold water may be used. Get medical attention if irritation occurs",
    "skin_contact": "Wash with soap and water. Cover the irritated skin with an emollient. Get medical attention if irritation develops. Cold water may be used",
    "inhalation": "If inhaled, remove to fresh air. If not breathing, give artificial respiration. If breathing is difficult, give oxygen. Get medical attention immediately",
    "ingestion": "Do NOT induce vomiting unless directed to do so by medical personnel. Never give anything by mouth to an unconscious person. If large quantities of this material are swallowed, call a physician immediately. Loosen tight clothing such as a collar, tie, belt or waistband",
    "small_spill": "Dilute with water and mop up, or absorb with an inert dry material and place in an appropriate waste disposal container. Finish cleaning by spreading water on the contaminated surface and dispose of according to local and regional authority requirements",
    "large_spill": "Stop leak if without risk. Do not get water inside container. Do not touch spilled material. Use water spray to reduce vapors. Prevent entry into sewers, basements or confined areas; dike if needed. Eliminate all ignition sources. Call for assistance on disposal. Finish cleaning by spreading water on the contaminated surface and allow to evacuate through the sanitary system. Be careful that the product is not present at a concentration level above TLV. Check TLV on the MSDS and with local authorities",
    "handling_precautions": "Keep away from heat. Keep away from sources of ignition. Empty containers pose a fire risk, evaporate the residue under a fume hood. Ground all equipment containing material. Do not ingest. Do not breathe gas/fumes/ vapor/spray. Wear suitable protective clothing. If ingested, seek medical advice immediately and show the container or the label. Keep away from incompatibles such as oxidizing agents, acids, alkalis",
    "storage": "Keep container tightly closed. Keep container in a cool, well-ventilated area",
    "engineering_controls": "Provide exhaust ventilation or other engineering controls to keep the airborne concentrations of vapors below their respective threshold limit value. Ensure that eyewash stations and safety showers are proximal to the work-station location",
    "personal_protection": "Safety glasses. Synthetic apron. Gloves (impervious). For most conditions, no respiratory protection should be needed. However, if material is heated or sprayed and if atmospheric levels exceed exposure guidelines, use an approved vapor (air purifying) respirator",
    "spill_protection": "Splash goggles. Full suit. Boots. Gloves. Suggested protective clothing might not be sufficient; consult a specialist BEFORE handling this product",
    "physical_state": "Liquid and syrupy",
    "odor": "Odorless",
    "color": "Clear Colorless",
    "molecular_weight": "62.07 grams per mole",
    "boiling_point": "197.6 degrees celsius, which is 387.7 degrees fahrenheit",
    "melting_point": "Negative 13.0 degrees celsius, which is 8.6 degrees fahrenheit",
    "stability": "The product is stable",
    "instability": "Excess heat or incompatible materials",
    "waste_disposal": "Waste must be disposed of in accordance with federal, state and local environmental control regulations",
    "dot_classification": "Not a DOT controlled material (United States)"
  },
  "batteries" : {
    "location": "in the garage",
    "common_name": "Batteries",
    "hazardous_ingredient": "Sulfuric Acid",
    "acute_health": "Very hazardous in case of skin contact (corrosive, irritant, permeator), of eye contact (irritant, corrosive), of ingestion, of inhalation. Liquid or spray mist may produce tissue damage particularly on mucous membranes of eyes, mouth and respiratory tract",
    "chronic_health": "The substance may be toxic to kidneys, lungs, heart, cardiovascular system, upper respiratory tract, eyes, teeth. Repeated or prolonged exposure to the substance can produce target organs damage. Repeated or prolonged contact with spray mist may produce chronic eye irritation and severe skin irritation. Repeated or prolonged exposure to spray mist may produce respiratory tract irritation leading to frequent attacks of bronchial infection. Repeated exposure to a highly toxic material may produce general deterioration of health by an accumulation in one or many human organs",
    "eye_contact": "Check for and remove any contact lenses. In case of contact, immediately flush eyes with plenty of water for at least 15 minutes. Cold water may be used. Get medical attention immediately",
    "skin_contact": "In case of contact, immediately flush skin with plenty of water for at least 15 minutes while removing contaminated clothing and shoes. Cover the irritated skin with an emollient. Cold water may be used. Wash clothing before reuse. Thoroughly clean shoes before reuse. Get medical attention immediately",
    "inhalation": "If inhaled, remove to fresh air. If not breathing, give artificial respiration. If breathing is difficult, give oxygen. Get medical attention immediately",
    "ingestion": "Do NOT induce vomiting unless directed to do so by medical personnel. Never give anything by mouth to an unconscious person. Loosen tight clothing such as a collar, tie, belt or waistband. Get medical attention if symptoms appear",
    "small_spill": "Dilute with water and mop up, or absorb with an inert dry material and place in an appropriate waste disposal container. If necessary: Neutralize the residue with a dilute solution of sodium carbonate",
    "large_spill": "Corrosive liquid. Poisonous liquid. Stop leak if without risk. Absorb with DRY earth, sand or other non-combustible material. Do not get water inside container. Do not touch spilled material. Use water spray curtain to divert vapor drift. Use water spray to reduce vapors. Prevent entry into sewers, basements or confined areas; dike if needed. Call for assistance on disposal. Neutralize the residue with a dilute solution of sodium carbonate. Be careful that the product is not present at a concentration level above TLV. Check TLV on the MSDS and with local authorities",
    "handling_precautions": "Keep locked up.. Keep container dry. Do not ingest. Do not breathe gas/fumes/ vapor/spray. Never add water to this product. In case of insufficient ventilation, wear suitable respiratory equipment. If ingested, seek medical advice immediately and show the container or the label. Avoid contact with skin and eyes. Keep away from incompatibles such as oxidizing agents, reducing agents, combustible materials, organic materials, metals, acids, alkalis, moisture. May corrode metallic surfaces. Store in a metallic or coated fiberboard drum using a strong polyethylene inner package",
    "storage": "Hygroscopic. Reacts. violently with water. Keep container tightly closed. Keep container in a cool, well-ventilated area. Do not store above 23 degrees celsius or 73.4 degrees fahrenheit",
    "engineering_controls": "Provide exhaust ventilation or other engineering controls to keep the airborne concentrations of vapors below their respective threshold limit value. Ensure that eyewash stations and safety showers are proximal to the work-station location",
    "personal_protection": "Face shield, Full suit, Vapor respirator, Be sure to use an approved/certified respirator or equivalent, Gloves, and Boots",
    "spill_protection": "Splash goggles. Full suit. Vapor respirator. Boots. Gloves. A self contained breathing apparatus should be used to avoid inhalation of the product. Suggested protective clothing might not be sufficient; consult a specialist BEFORE handling this product",
    "physical_state": "Liquid, Thick oily liquid",
    "odor": "Odorless, but has a choking odor when hot",
    "color": "Colorless",
    "molecular_weight": "98.08 grams per mole",
    "boiling_point": "270 degrees celsius, which is 518 degrees fahrenheit",
    "melting_point": "Negative 35 degrees celsius, which is Negative 31 degrees fahrenheit",
    "stability": "The product is stable",
    "instability": "Conditions to Avoid: Incompatible materials, excess heat, combustible material materials, organic materials, exposure to moist air or water, oxidizers, amines, bases. Always add the acid to water, never the reverse. Incompatibility with various substances: Reactive with oxidizing agents, reducing agents, combustible materials, organic materials, metals, acids, alkalis, moisture. Corrosivity: Extremely corrosive in presence of aluminum, of copper, of stainless steel(316). Highly corrosive in presence of stainless steel(304)",
    "waste_disposal": "Sulfuric acid may be placed in sealed container or absorbed in vermiculite, dry sand, earth, or a similar material. It may also be diluted and neutralized. Be sure to consult with local or regional authorities (waste regulators) prior to any disposal. Waste must be disposed of in accordance with federal, state and local environmental control regulations",
    "dot_classification": "Class 8: Corrosive material"
  },
  "windshield washer fluid" : {
    "location": "in the garage",
    "common_name": "Windshield Washer Fluid",
    "hazardous_ingredient": "Methanol",
    "acute_health": "Hazardous in case of skin contact (irritant), of eye contact (irritant), of ingestion, of inhalation. Slightly hazardous in case of skin contact (permeator). Severe over-exposure can result in death",
    "chronic_health": "The substance is toxic to eyes. The substance may be toxic to blood, kidneys, liver, brain, peripheral nervous system, upper respiratory tract, skin, central nervous system (CNS), optic nerve. Repeated or prolonged exposure to the substance can produce target organs damage. Repeated exposure to a highly toxic material may produce general deterioration of health by an accumulation in one or many human organs",
    "eye_contact": "Check for and remove any contact lenses. Immediately flush eyes with running water for at least 15 minutes, keeping eyelids open. Cold water may be used. Get medical attention",
    "skin_contact": "In case of contact, immediately flush skin with plenty of water for at least 15 minutes while removing contaminated clothing and shoes. Cover the irritated skin with an emollient. Cold water may be used.Wash clothing before reuse. Thoroughly clean shoes before reuse. Get medical attention immediately",
    "inhalation": "If inhaled, remove to fresh air. If not breathing, give artificial respiration. If breathing is difficult, give oxygen. Get medical attention immediately",
    "ingestion": "If swallowed, do not induce vomiting unless directed to do so by medical personnel. Never give anything by mouth to an unconscious person. Loosen tight clothing such as a collar, tie, belt or waistband. Get medical attention immediately",
    "small_spill": "Dilute with water and mop up, or absorb with an inert dry material and place in an appropriate waste disposal container",
    "large_spill": "Flammable liquid. Poisonous liquid. Keep away from heat. Keep away from sources of ignition. Stop leak if without risk. Absorb with DRY earth, sand or other non-combustible material. Do not get water inside container. Do not touch spilled material. Use water spray to reduce vapors. Prevent entry into sewers, basements or confined areas; dike if needed. Call for assistance on disposal. Be careful that the product is not present at a concentration level above TLV. Check TLV on the MSDS and with local authorities",
    "handling_precautions": "Keep locked up.. Keep away from heat. Keep away from sources of ignition. Ground all equipment containing material. Do not ingest. Do not breathe gas/fumes/ vapor/spray. Wear suitable protective clothing. In case of insufficient ventilation, wear suitable respiratory equipment. If ingested, seek medical advice immediately and show the container or the label. Avoid contact with skin and eyes. Keep away from incompatibles such as oxidizing agents, metals, acids",
    "storage": "Store in a segregated and approved area. Keep container in a cool, well-ventilated area. Keep container tightly closed and sealed until ready for use. Avoid all possible sources of ignition (spark or flame)",
    "engineering_controls": "Provide exhaust ventilation or other engineering controls to keep the airborne concentrations of vapors below their respective threshold limit value. Ensure that eyewash stations and safety showers are proximal to the work-station location",
    "personal_protection": "Splash goggles. Lab coat. Vapor respirator. Be sure to use an approved/certified respirator or equivalent. Gloves",
    "spill_protection": "Splash goggles. Full suit. Vapor respirator. Boots. Gloves. A self contained breathing apparatus should be used to avoid inhalation of the product. Suggested protective clothing might not be sufficient; consult a specialist BEFORE handling this product",
    "physical_state": "Liquid",
    "odor": "Alcohol like, Pungent when crude",
    "color": "Colorless",
    "molecular_weight": "32.04 grams per mole",
    "boiling_point": "64.5 degrees celsius, which is 148.1 degrees fahrenheit",
    "melting_point": "Negative 97.8 degrees celsius, which is Negative 144 degrees fahrenheit",
    "stability": "The product is stable",
    "instability": " Heat, ingnition sources, incompatible materials",
    "waste_disposal": "Waste must be disposed of in accordance with federal, state and local environmental control regulations",
    "dot_classification": "CLASS 3: Flammable liquid"
  },
  "" : {
    "location": "",
    "common_name": "",
    "hazardous_ingredient": "",
    "acute_health": "",
    "chronic_health": "",
    "eye_contact": "",
    "skin_contact": "",
    "inhalation": "",
    "ingestion": "",
    "small_spill": "",
    "large_spill": "",
    "handling_precautions": "",
    "storage": "",
    "engineering_controls": "",
    "personal_protection": "",
    "spill_protection": "",
    "physical_state": "",
    "odor": "",
    "color": "",
    "molecular_weight": "",
    "boiling_point": "",
    "melting_point": "",
    "stability": "",
    "instability": "",
    "waste_disposal": "",
    "dot_classification": ""
  }
};
